### PR TITLE
Extract IHttpClientFactory, IHttpMessageHandlerFactory and ITypedHttpClientFactory<TClient> to an abstractions assembly.

### PR DESCRIPTION
**Pull request by paulomorgado**
These abstractions are also useful for non-server applications.

Splitting them allows for libraries that do not depend on server ASP.NET Core.

Allows also for other implementations without taking a dependency on the provided implementation.

### CODE REVIEW

**Comment by rynowak** [comment]
Hi @paulomorgado - have you considered using [](https://github.com/aspnet/Hosting/blob/master/samples/GenericHostSample/ProgramHelloWorld.cs)generic host for this? The client factory intentionally don't depend on anything from ASP.NET Core - just the Microsoft.Extensions libraries.

Do you plan to create and ship an alternative implementation of this for your use case?

**Comment by paulomorgado** [comment]
@rynowak, my components/libraries can run on console applications, windows services, system.web and any other runtime.

But, besides that, I like the model of having abstractions assemblies used by other Microsoft.Extensions Libraries. I use them a lot and I haven't written an ASP.NET Core or .NET Core application ever.

**Comment by rynowak** [comment]
> have you considered using generic host for this? The client factory intentionally don't depend on anything from ASP.NET Core - just the Microsoft.Extensions libraries.

> Do you plan to create and ship an alternative implementation of this for your use case?

**Comment by paulomorgado** [comment]
> have you considered using generic host for this? The client factory intentionally don't depend on anything from ASP.NET Core - just the Microsoft.Extensions libraries.

Not really compatible with System.Web. Is it?

> Do you plan to create and ship an alternative implementation of this for your use case?

I already have implemented it. It just take a bit of remaining to become `IHttpClientFactory` and `IHttpMessageHandlerFactory`.

**Comment by rynowak** [comment]
> Not really compatible with System.Web. Is it?

Yes, absolutely. The generic host libraries target netstandard2.0 and net461 - they can be used to bootstrap the Microsoft.Extensions libraries including logging and configuration into any .NET process.

**Comment by paulomorgado** [comment]
Cool! Do you have an example on how I can set up a generic host on top of System.Web (ASP.NET WebForms, ASP.NET MVC and ASP.NET Web API) hosting?

**Comment by rynowak** [comment]
Here's a general purpose example: https://github.com/aspnet/Hosting/blob/master/samples/GenericHostSample/ProgramFullControl.cs - I think you'd primarily be interested in the services configuration part for HttpClient Factory.

If you're on System.Web then you'd want to call `StartAsync` and `StopAsync` from the relevant events in Global.asax.cs (I don't remember the event names)

**Comment by paulomorgado** [comment]
I'll have a look at it.

It does look like a very convoluted way of using this for System.Web (or OWIN, for that matter).

**Comment by natemcmaster** [comment]
Hey @paulomorgado, I'm going to archive this repo later today which makes it read-only. HttpClientFactory is still under active development in this repo now: https://github.com/aspnet/Extensions/. If you'd like to continue this work, you'll have to rebase your changes on that repo and create a new PR.

Thanks,
Nate

**Pull request closed without merging**
